// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppSettings 全局设置,与前端 AppSettings 类型对应。
 */
export interface AppSettings {
    "primaryDns": string;
    "secondaryDns": string;

    /**
     * 秒
     */
    "queryInterval": number;
    "enableIpv6": boolean;
    "autoStart": boolean;
    "minToTray": boolean;
    "dnsMode": DnsMode;
}

/**
 * DnsMode DNS 解析模式。
 * 本期仅支持 UDP 直连查询(设置中的主备 DNS 服务器);DoH/DoT 暂未实现。
 */
export enum DnsMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DnsModeUDP = "UDP",
};

/**
 * LogEntry 运行日志条目,与前端 LogEntry 类型对应。
 */
export interface LogEntry {
    "id": number;
    "time": string;
    "type": LogLevel;
    "text": string;
}

/**
 * LogLevel 日志级别。
 */
export enum LogLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LogLevelInfo = "info",
    LogLevelWarn = "warn",
    LogLevelError = "error",
    LogLevelSuccess = "success",
};

/**
 * NetworkInterface 物理网卡。
 * IPv4Gateway/IPv6Gateway 为网关转发所需:AddHostRoute 将解析出的 IP
 * 路由到该网卡的网关(非 on-link 直连),故无 IPv4 网关的网卡不可用于本服务。
 */
export interface NetworkInterface {
    "id": string;
    "name": string;
    "type": NicType;
    "active": boolean;
    "ipv4Gateway": string;
    "ipv6Gateway": string;
}

/**
 * NicType 物理网卡类型。
 */
export enum NicType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NicTypeWired = "wired",
    NicTypeWireless = "wireless",
};

/**
 * RouteRule 路由规则条目,与前端 RouteRule 类型对应。
 */
export interface RouteRule {
    "id": string;
    "domain": string;
    "port": string;
    "alias": string;
    "checked": boolean;
    "resolvedIp": string;
    "lastResolvedSec": number;
}

/**
 * RouteRuleInput 新建/编辑路由规则时提交的表单数据。
 */
export interface RouteRuleInput {
    "domain": string;
    "port": string;
    "alias": string;
}

/**
 * ServiceStartResult 服务启动结果,与前端 ServiceStartResult 类型对应。
 */
export interface ServiceStartResult {
    "running": boolean;
    "nicId": string;
    "rules": RouteRule[] | null;
}
