// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EngineService 核心路由服务引擎控制,暴露给前端绑定调用。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

/**
 * GetServiceStatus 返回当前服务状态快照,供前端轮询刷新实时解析结果。
 */
export function GetServiceStatus(): $CancellablePromise<models$0.ServiceStartResult> {
    return $Call.ByID(1203623130);
}

/**
 * StartService 启动核心路由服务:对勾选的规则做 DNS 解析,
 * 并将解析出的 IP 以临时主机路由绑定到指定网卡。
 * 返回启动后的服务状态快照(含已解析结果)。
 * 重复启动返回错误;DNS 服务器与解析间隔取自当前持久化设置。
 */
export function StartService(nicId: string, rules: models$0.RouteRule[] | null): $CancellablePromise<models$0.ServiceStartResult> {
    return $Call.ByID(659576772, nicId, rules);
}

/**
 * StopService 停止核心路由服务,并清理全部已添加的临时路由。
 * 服务未运行时返回 nil(幂等)。
 */
export function StopService(): $CancellablePromise<void> {
    return $Call.ByID(1937052250);
}
