// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as EngineService from "./engineservice.js";
import * as NicsService from "./nicsservice.js";
import * as RoutesService from "./routesservice.js";
import * as SettingsService from "./settingsservice.js";
export {
    EngineService,
    NicsService,
    RoutesService,
    SettingsService
};
