// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NicsService 网卡查询服务,暴露给前端绑定调用。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

/**
 * GetNetworkInterfaces 返回本机当前活动的物理网卡列表(有线/无线)。
 * 非 Windows 平台返回空列表。
 */
export function GetNetworkInterfaces(): $CancellablePromise<models$0.NetworkInterface[] | null> {
    return $Call.ByID(2595672272);
}
