// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RoutesService 路由规则 CRUD 服务,暴露给前端绑定调用。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

/**
 * CreateRoute 新建一条路由规则并持久化,返回创建后的完整条目。
 * 与前端 mock 行为一致:新建条目默认勾选(checked=true)。
 */
export function CreateRoute(input: models$0.RouteRuleInput): $CancellablePromise<models$0.RouteRule> {
    return $Call.ByID(1465115028, input);
}

/**
 * DeleteRoute 删除一条路由规则。
 */
export function DeleteRoute(id: string): $CancellablePromise<void> {
    return $Call.ByID(4240233145, id);
}

/**
 * ListRoutes 返回全部路由规则(持久化数据)。
 */
export function ListRoutes(): $CancellablePromise<models$0.RouteRule[] | null> {
    return $Call.ByID(4024100613);
}

/**
 * UpdateRoute 更新一条已存在的路由规则(仅更新 domain/port/alias,
 * 保留 checked/resolvedIp/lastResolvedSec 等运行期字段)。
 */
export function UpdateRoute(id: string, input: models$0.RouteRuleInput): $CancellablePromise<models$0.RouteRule> {
    return $Call.ByID(1759914095, id, input);
}
