// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 全局设置读写服务,暴露给前端绑定调用。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

/**
 * GetSettings 返回当前全局设置(持久化数据,缺失字段自动回退默认值)。
 */
export function GetSettings(): $CancellablePromise<models$0.AppSettings> {
    return $Call.ByID(3034808949);
}

/**
 * SaveSettings 校验并持久化全局设置。
 */
export function SaveSettings(settings: models$0.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(2662658340, settings);
}
