// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateRoute(arg1:models.RouteRuleInput):Promise<models.RouteRule>;

export function DeleteRoute(arg1:string):Promise<void>;

export function GetNetworkInterfaces():Promise<Array<models.NetworkInterface>>;

export function GetServiceStatus():Promise<models.ServiceStartResult>;

export function GetSettings():Promise<models.AppSettings>;

export function ListRoutes():Promise<Array<models.RouteRule>>;

export function SaveSettings(arg1:models.AppSettings):Promise<void>;

export function StartService(arg1:string,arg2:Array<models.RouteRule>):Promise<models.ServiceStartResult>;

export function StopService():Promise<void>;

export function UpdateRoute(arg1:string,arg2:models.RouteRuleInput):Promise<models.RouteRule>;
