// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRoute(arg1) {
  return window['go']['main']['App']['CreateRoute'](arg1);
}

export function DeleteRoute(arg1) {
  return window['go']['main']['App']['DeleteRoute'](arg1);
}

export function GetNetworkInterfaces() {
  return window['go']['main']['App']['GetNetworkInterfaces']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListRoutes() {
  return window['go']['main']['App']['ListRoutes']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function UpdateRoute(arg1, arg2) {
  return window['go']['main']['App']['UpdateRoute'](arg1, arg2);
}
